// Japanese website copy, keyed by its English source.
export const japanese: Record<string, string> = {
  "MAC ONLY · BUILT-IN MCP SERVER": "MAC専用 · 内蔵MCPサーバー",
  "iPHONE · PORTRAIT": "iPHONE · 縦向き",
  "Termind: AI-driven remote workspace for Mac, iPhone, and iPad": "Termind：Mac、iPhone、iPadのためのAIリモートワークスペース",
  "AI-driven remote work with SSH, SFTP, live metrics, and built-in Tailscale. Bring your own model key and control what AI can do.": "SSH、SFTP、リアルタイム監視、内蔵Tailscaleをひとつに。自分のモデルキーを使い、AIの権限も自分で決められます。",
  "SSH · SFTP · AI": "SSH · SFTP · AI",
  "Your servers.": "サーバーを、",
  "Within reach.": "もっと身近に。",
  "Connect. Transfer. Let AI assist. One workspace for Mac, iPhone, and iPad.": "つなぐ。転送する。AIと進める。Mac、iPhone、iPadで使える、ひとつのワークスペース。",
  "Download Termind on the App Store": "App StoreでTermindをダウンロード",
  "": "からダウンロード",
  "Explore Termind": "Termindを見る",
  "System requirements": "システム要件",
  "Termind workspace and AI Assistant": "TermindのワークスペースとAIアシスタント",
  "Termind multi-pane workspace on Mac": "Mac上のTermindマルチペインワークスペース",
  "Termind AI Assistant on the iPhone Duo outer display": "iPhone Duoの外側ディスプレイに表示されたTermind AIアシスタント",
  "Termind SSH terminal on iPhone": "iPhone上のTermind SSHターミナル",
  "AT YOUR DESK. ON THE GO.": "デスクでも、外出先でも。",
  "Multi-pane control room": "マルチペインの操作拠点",
  "A terminal in reach": "手元にあるターミナル",
  "Full SFTP and live metrics": "充実したSFTPとリアルタイム監視",
  "BUILT AROUND THE WORK": "作業に寄り添う設計",
  "Less switching.": "切り替えを減らして、",
  "More doing.": "作業をスムーズに。",
  "A real terminal, wherever you are.": "本格ターミナルを、いつでも。",
  "A full terminal, made for touch. Find output, recall a snippet, and keep working wherever you are.": "タッチ操作に最適化した本格ターミナル。出力の検索も、スニペットの呼び出しも。どこにいても作業を続けられます。",
  "Touch-first terminal controls": "タッチ操作に最適化したコントロール",
  "Snippets and command history": "スニペットとコマンド履歴",
  "Command Generator never presses Return": "コマンド生成機能が勝手に実行することはありません",
  "SSH terminal with production service output on iPhone": "本番サービスの出力を表示するiPhoneのSSHターミナル",
  "Move files. Keep your flow.": "ファイル転送も、そのまま。",
  "Browse, preview, drag to upload, and track concurrent transfers. Open the same live path in SSH without rebuilding context.": "閲覧、プレビュー、ドラッグでアップロード。同時転送の進捗も確認でき、現在のパスをそのままSSHで開けます。",
  "A complete SFTP workflow, built for touch": "タッチで完結するSFTPワークフロー",
  "Concurrent transfers continue in the background": "バックグラウンドでも並行転送",
  "Open the same live path in SSH": "同じパスをSSHで開く",
  "SFTP file browser on the unfolded iPhone Duo": "展開したiPhone Duo上のSFTPファイルブラウザ",
  "SFTP · FILE TRANSFER": "SFTP · ファイル転送",
  "Your servers, at a glance.": "サーバーの状態を、ひと目で。",
  "CPU, memory, disks, and processes in one view. Spot an issue and act over the same SSH connection.": "CPU、メモリ、ディスク、プロセスを一覧表示。異常を見つけたら、同じSSH接続ですぐに対応できます。",
  "Server metrics and processes on iPad": "iPad上のサーバーメトリクスとプロセス一覧",
  "Live over your SSH connection": "SSH接続でリアルタイムに取得",
  "Takes action.": "実行できる。",
  "Remembers.": "記憶もできる。",
  "Investigate issues and take action with AI. Bring your own model key. You choose what it can do.": "AIと一緒に問題を調べ、対処する。モデルキーは自分のものを。できることは、あなたが決めます。",
  "Optional Hermes Memory remembers context between conversations. Off by default, stored on this device, and yours to review, edit, or delete.": "必要に応じてHermes Memoryを有効にすると、会話をまたいで背景や好みを記憶します。初期設定ではオフ。データはこのデバイスに保存され、いつでも確認・編集・削除できます。",
  "Your model. Your permissions.": "モデルも、権限も、あなた次第。",
  "Optional, device-local memory": "記憶は任意。このデバイスだけに保存。",
  " is the open-source agent runtime behind Termind’s AI Assistant.": "は、TermindのAIアシスタントを支えるオープンソースのエージェントランタイムです。",
  "Permission-aware AI Assistant on the iPhone Duo outer display": "iPhone Duoの外側ディスプレイ上で権限を確認するAIアシスタント",
  "Your Vault, protected by design.": "Vaultを、設計から安全に。",
  "Keep hosts, snippets, Metrics, and settings—including Connections preferences—in sync through your private iCloud database, while passwords and keys stay separately protected by Keychain.": "ホスト、スニペット、メトリクス、接続設定を含む各種設定は、プライベートiCloudデータベースで同期。パスワードと鍵は、キーチェーンで別途保護します。",
  "Vault on iPad": "iPad上のVault",
  "Vault on iPhone": "iPhone上のVault",
  "GO DEEPER ON MAC": "MACでもっと深く",
  "Your full control room.": "作業のすべてを、ひとつに。",
  "Compose SSH, Telnet, SFTP, and serial sessions into multi-pane workspaces and broadcast input between terminals for free. Pro adds the built-in loopback-only MCP server for audited SSH/SFTP tools.": "SSH、Telnet、SFTP、シリアル接続をマルチペインで整理し、複数のターミナルへ一括入力。すべて無料で使えます。Proなら、SSH/SFTPツールの呼び出しを記録する内蔵MCPサーバーも利用できます。既定ではループバック接続のみを受け付けます。",
  "Multi-pane": "マルチペイン",
  "Serial": "シリアル接続",
  "Built-in MCP server": "内蔵MCPサーバー",
  "Multi-pane Termind workspace on Mac": "Mac上のTermindマルチペインワークスペース",
  "Give local AI": "ローカルAIに、",
  "secure remote tools.": "安全なリモート操作を。",
  "Turn on Termind’s built-in MCP server and local clients can list saved hosts, execute SSH commands, and read or write through SFTP. Expose tools one by one, keep access on loopback by default, and retain an audit trail for every external call.": "内蔵MCPサーバーを有効にすると、ローカルクライアントから保存済みホストの一覧取得、SSHコマンドの実行、SFTPでの読み書きができます。ツールは個別に公開でき、既定ではループバック接続のみ。外部からの呼び出しはすべて監査ログに記録します。",
  "Loopback only by default": "既定ではローカル接続のみ",
  "Per-tool controls": "ツールごとに権限を設定",
  "Calls audited": "呼び出しを記録",
  "Local AI clients connect through Termind MCP to SSH and SFTP tools": "ローカルAIクライアントがTermind MCP経由でSSHとSFTPツールに接続する図",
  "Codex is a product of OpenAI; Claude Code is a product of Anthropic; Pi is developed by Mario Zechner. Names and marks belong to their respective owners and are shown only to describe compatibility. Termind is not affiliated with, sponsored by, or endorsed by them.": "CodexはOpenAI、Claude CodeはAnthropicの製品です。PiはMario Zechnerが開発しています。名称と商標は各権利者に帰属し、互換性の説明のみに使用しています。Termindはこれらの組織・開発者と提携しておらず、スポンサー支援や推奨を受けていません。",
  "MULTI-CONNECTION PORT FORWARDING": "複数接続のポート転送",
  "More connections. Less waiting.": "接続を増やして、待ち時間を短く。",
  "Multiple SSH connections. 2.54× the throughput of single-connection mode in our loopback test.": "複数のSSH接続で並行転送。ループバックテストで、単一接続の2.54倍のスループットを記録しました。",
  "2.54 times the throughput": "2.54倍のスループット",
  "THE THROUGHPUT": "スループット",
  "Throughput benchmark in Mbps per direction: Termind with 12 connections, 3,869.7; Termind with one connection, 1,524.2; Termius, 1,628.2; OpenSSH, 1,585.4.": "片方向のスループット比較（Mbps）：Termind 12接続は3,869.7、Termind 1接続は1,524.2、Termiusは1,628.2、OpenSSHは1,585.4。",
  "12 connections": "12接続",
  "1 connection": "1接続",
  "Loopback · 64 concurrent TCP flows · Median of 5 runs": "ループバック · TCP 64フロー同時通信 · 5回の中央値",
  "Tested September 20, 2026": "測定日：2026年9月20日",
  "Useful payload per direction (Mbps) · higher is better": "片方向の実効転送量（Mbps）· 高いほど高速",
  "Subscribe annually—or keep it forever.": "年間プランでも、買い切りでも。",
  "Core SSH, Telnet, SFTP, terminal uploads, snippets, Command Generator, and port forwarding stay free, as do serial sessions, multi-pane workspaces, and input broadcasting on Mac. Annual or lifetime Pro unlocks built-in Tailscale, the AI Assistant with optional Hermes Memory, monitoring for more than 3 servers, remote MCP clients, iCloud sync, and the built-in MCP server on Mac.": "基本のSSH、Telnet、SFTP、ターミナルからのアップロード、スニペット、コマンド生成、ポート転送は無料。Macのシリアル接続、マルチペイン、一括入力も無料です。年間または買い切りのProで、内蔵Tailscale、任意のHermes Memoryに対応したAIアシスタント、4台以上のサーバー監視、リモートMCPクライアント、iCloud同期、Macの内蔵MCPサーバーが使えます。",
  "Regional App Store pricing · Family Sharing": "価格は各地域のApp Storeで確認 · ファミリー共有に対応",
  "Available offers are shown by the App Store. AI provider costs are separate.": "利用可能なオファーはApp Storeに表示されます。AIプロバイダーの利用料は別途かかります。",
  "See all plans": "すべてのプランを見る",
  "SECURITY, BY DESIGN": "設計から、安全に",
  "From your key": "あなたの鍵から、",
  "to every action.": "ひとつひとつの操作まで。",
  "See how Termind protects SSH credentials at rest and in memory, verifies server identity, and places clear boundaries around the Assistant and built-in MCP server.": "保存時とメモリ内のSSH認証情報の保護、サーバーの本人確認、アシスタントと内蔵MCPサーバーの権限制御について紹介します。",
  "Explore security design": "セキュリティ設計を見る",
  "PLAIN-LANGUAGE POLICY": "わかりやすいポリシー",
  "Know exactly": "データの行き先を、",
  "where data goes.": "明確に。",
  "Every meaningful data path is documented—from local storage and Keychain to iCloud, remote hosts, search engines, and your selected model provider.": "ローカルストレージやキーチェーンから、iCloud、リモートホスト、検索エンジン、選択したモデルプロバイダーまで。重要なデータの流れを明記しています。",
  "Open privacy policy": "プライバシーポリシーを見る",
  "Ready when you are.": "いつでも、つながる準備を。",
  "Your next connection starts here.": "次の接続は、ここから。",
  "Download on the App Store": "App Storeからダウンロード",
  "TAILSCALE, BUILT IN": "TAILSCALEを内蔵",
  "Your Tailnet.": "あなたのTailnetを、",
  "Already in Termind.": "Termindから直接。",
  "Connect to your private servers. No separate Tailscale app or system VPN setup needed.": "プライベートサーバーに接続。Tailscaleアプリの別途インストールや、システムVPNの設定は不要です。",
  "How to connect your Tailnet": "Tailnetへの接続方法",
  "YOUR PRIVATE NETWORK": "プライベートネットワーク",
  "Connection diagram: Termind connects through your Tailnet to your development server, production server, and home lab.": "接続図：TermindがTailnet経由で開発サーバー、本番サーバー、ホームラボに接続します。",
  "Your workspace": "あなたのワークスペース",
  "Development": "開発環境",
  "Production": "本番環境",
  "Home lab": "ホームラボ",
  "Enable Tailscale SSH on the servers you want to reach. Your Tailnet’s SSH policy controls access.": "接続先のサーバーでTailscale SSHを有効にしてください。アクセスはTailnetのSSHポリシーで管理されます。",
  "Termind’s built-in Tailscale support is powered by ": "Termindの内蔵Tailscale機能には、",
  ".": "。",
  "Tailscale is a trademark of Tailscale Inc. The name is used here only to describe compatibility. Termind is not affiliated with, sponsored by, or endorsed by Tailscale Inc.": "TailscaleはTailscale Inc.の商標です。名称は互換性の説明のみに使用しています。TermindはTailscale Inc.と提携しておらず、スポンサー支援や推奨を受けていません。",
  "A gift for our Telegram community": "Telegramコミュニティへのプレゼント",
  "Yours for free.": "無料で手に入れるチャンス。",
  "Join the Termind Telegram channel and group, then enter our draw through the bot for a chance to win a free Pro redeem code every Thursday. Check the channel for announcements and results.": "TermindのTelegramチャンネルとグループに参加し、ボットから毎週木曜日の抽選に応募すると、Proの無料引き換えコードが当たります。お知らせと抽選結果はチャンネルでご確認ください。",
  "Join the Telegram channel": "Telegramチャンネルに参加",
  "Three steps to enter and redeem": "応募から引き換えまでの3ステップ",
  "Join the channel and group": "チャンネルとグループに参加",
  "Subscribe to the channel": "チャンネルを購読",
  " and ": "して、",
  "join the community group": "コミュニティグループに参加",
  "Enter the Thursday draw": "木曜日の抽選に応募",
  "Open the draw bot": "抽選ボットを開き",
  ", tap Start, then Enter Draw. The draw takes place every Thursday.": "、「開始」、続いて「抽選に応募」をタップ。抽選は毎週木曜日に行います。",
  "Win and redeem Pro": "当選したらProを引き換え",
  "Winners receive their code in a private message from the bot. Use the App Store link provided to redeem it before it expires.": "当選者には、ボットから個別メッセージでコードが届きます。記載のApp Storeリンクから、有効期限内に引き換えてください。",
  "Entry does not guarantee a win; non-winners can enter the next draw. Redemption eligibility and validity are determined by Apple.": "応募しても当選するとは限りません。落選した場合は次回も応募できます。引き換え資格と有効期限はAppleの規定に従います。",
  "Termind home": "Termindホーム",
  "Primary navigation": "メインナビゲーション",
  "Pricing": "料金",
  "Compare": "比較",
  "Security": "セキュリティ",
  "Privacy": "プライバシー",
  "Support": "サポート",
  "Data handling, in plain language": "データの取り扱いを、わかりやすく",
  "Privacy Policy": "プライバシーポリシー",
  "Termind is local-first. You choose which services to connect and whether to share diagnostic data.": "Termindはローカル優先。接続するサービスも、診断データを共有するかどうかも、あなたが選べます。",
  "Effective": "施行日",
  "October 3, 2026": "2026年10月3日",
  "Version": "バージョン",
  "Table of contents": "目次",
  "Contents": "目次",
  "Overview": "概要",
  "Data on your device": "デバイス上のデータ",
  "iCloud & Keychain": "iCloudとキーチェーン",
  "Purchases and subscriptions": "購入とサブスクリプション",
  "AI & MCP": "AIとMCP",
  "Web Search": "ウェブ検索",
  "Remote connections": "リモート接続",
  "Camera & speech": "カメラと音声",
  "Diagnostics": "診断",
  "This website": "このウェブサイト",
  "Your controls": "ユーザーによる管理",
  "Contact": "お問い合わせ",
  "We do not sell personal information, show advertising, use cross-app tracking, or include third-party behavioral analytics SDKs in the app. No Termind account is required.": "個人情報の販売、広告表示、アプリ間のトラッキングは行いません。アプリに第三者の行動分析SDKも組み込んでいません。Termindアカウントは不要です。",
  "Termind is a client application. When you use AI, search, iCloud, Tailscale, speech, or remote connections, the relevant service provider processes what it receives under its own terms. Termind does not place a hosted proxy between you and those providers.": "Termindはクライアントアプリです。AI、検索、iCloud、Tailscale、音声機能、リモート接続を利用すると、関連するサービス提供者が、受信した情報を各自の規約に従って処理します。Termindが運営するプロキシサーバーを経由することはありません。",
  "Data stored on your device": "デバイスに保存されるデータ",
  "To provide its features, Termind stores the following information on your device:": "機能を提供するため、Termindは次の情報をデバイスに保存します。",
  "Vault metadata such as host names, addresses, ports, usernames, groups, tags, identity labels, public-key fingerprints, Known Hosts entries, snippets, and port-forwarding rules.": "ホスト名、アドレス、ポート、ユーザー名、グループ、タグ、認証情報のラベル、公開鍵のフィンガープリント、既知のホスト、スニペット、ポート転送ルールなどのVaultメタデータ。",
  "Tailscale group configuration, this device’s Tailnet profile, and cached peer information such as device names, addresses, public SSH host keys, online status, and key-expiry information. Private node state is stored separately in Keychain, as described in the Tailscale section.": "Tailscaleグループの設定、このデバイスのTailnetプロファイル、デバイス名・アドレス・SSHホスト公開鍵・オンライン状態・鍵の有効期限など、検出したピアのキャッシュ。非公開のノード状態は、Tailscaleの項で説明するとおり、キーチェーンに別途保存します。",
  "Connection history, including the host, connection type and times, together with the name or model used to identify the device where the connection was made.": "ホスト、接続の種類と日時、接続元デバイスを識別するための名前またはモデルを含む接続履歴。",
  "AI provider and model configuration, role assignments, the last selected model, MCP client configuration and tool policies, skill text and enabled state, Web Search preferences, terminal themes and integration options, and Connections preferences such as SSH Max Sessions and file-transfer concurrency. Enabling settings sync also stores these settings in your private iCloud database.": "AIプロバイダーとモデルの設定、役割の割り当て、最後に選択したモデル、MCPクライアント設定とツールポリシー、スキルの本文と有効状態、ウェブ検索の設定、ターミナルのテーマと統合オプション、SSH Max Sessionsやファイル転送の同時実行数などの接続設定。設定の同期を有効にすると、これらはプライベートiCloudデータベースにも保存されます。",
  "Conversations, messages, agent tool calls and results, security-review records, command history, workspace state, and app settings.": "会話、メッセージ、エージェントのツール呼び出しと結果、安全性の審査記録、コマンド履歴、ワークスペースの状態、アプリ設定。",
  "Context attachments you import and per-conversation scratch files until you delete the related conversation.": "インポートしたコンテキスト添付ファイルと会話ごとの一時作業ファイル。関連する会話を削除するまで保持されます。",
  "This data is not automatically sent to the Termind developer. The operating system, device backups, or other software you install may access or back up local files according to their own settings.": "これらのデータがTermindの開発者へ自動送信されることはありません。OS、デバイスのバックアップ、インストールした他のソフトウェアは、それぞれの設定に従い、ローカルファイルにアクセスしたりバックアップしたりする場合があります。",
  "Vault sync": "Vaultの同期",
  "When “iCloud Sync” is on and “Vault” is selected, Vault data, connection history, and the device names or models used to identify where connections were made are stored in the private iCloud database for your Apple ID. Device information is used only to distinguish connection-history sources across your devices. It is transferred only through your private iCloud database; the Termind developer does not receive or collect it. Apple processes synced data under its terms.": "「iCloud同期」をオンにし、「Vault」を選択すると、Vaultデータ、接続履歴、接続元を識別するデバイス名またはモデルが、Apple IDのプライベートiCloudデータベースに保存されます。デバイス情報は、複数のデバイス間で接続履歴の発生元を区別する目的にのみ使用します。転送はプライベートiCloudデータベース経由に限られ、Termindの開発者が受信・収集することはありません。同期データはAppleが同社の規約に従って処理します。",
  "Tailscale group configuration can sync with Vault. Tailnet sign-in and the discovered peer cache stay on the current device; see": "Tailscaleのグループ設定はVaultと同期できます。Tailnetのログイン状態と検出したピアのキャッシュは現在のデバイスに残ります。詳しくは、",
  "Tailscale data handling": "Tailscaleのデータ取り扱い",
  "Metrics sync": "メトリクスの同期",
  "“Metrics” is selected by default. When iCloud Sync is on, monitored host identifiers, pause state, disk and network-interface selections, and card order sync through CloudKit. Host addresses and credentials remain managed separately by Vault and Keychain; live samples, metric history, authentication state, and menu-bar preferences do not sync. A configuration is retained but hidden when its host is unavailable on the current device.": "「メトリクス」は初期設定で選択されています。iCloud同期をオンにすると、監視対象ホストの識別子、一時停止状態、ディスクとネットワークインターフェイスの選択、カードの順序がCloudKit経由で同期されます。ホストのアドレスと認証情報はVaultとキーチェーンで別途管理され、リアルタイムのサンプル、メトリクス履歴、認証状態、メニューバー設定は同期されません。現在のデバイスでホストを利用できない場合、設定は保持されますが非表示になります。",
  "Settings sync": "設定の同期",
  "iCloud sync is a Pro feature with one main switch and checkboxes for the data to sync. Vault, Metrics, and Settings are all selected by default. When the main switch is on and “Settings” is selected, provider and endpoint settings, model lists and custom parameters, role assignments, the last selected model, MCP client configuration and tool policies, complete skill text and enabled state, Web Search preferences, terminal preferences, and Connections preferences sync through CloudKit to your Apple account’s private iCloud database. Connections preferences include SSH Max Sessions and file-transfer concurrency. Configuration includes complete custom terminal configuration text and custom MCP header names and values; use the dedicated credential fields for secrets.": "iCloud同期はPro機能で、全体のスイッチと同期対象のチェックボックスがあります。Vault、メトリクス、設定は、初期設定ですべて選択されています。全体のスイッチをオンにし、「設定」を選択すると、プロバイダーとエンドポイントの設定、モデル一覧とカスタムパラメータ、役割の割り当て、最後に選択したモデル、MCPクライアント設定とツールポリシー、スキルの全文と有効状態、ウェブ検索、ターミナル、接続の各設定が、CloudKit経由でAppleアカウントのプライベートiCloudデータベースに同期されます。接続設定にはSSH Max Sessionsとファイル転送の同時実行数が含まれます。カスタムターミナル設定の全文、カスタムMCPヘッダーの名前と値も同期対象です。秘密情報には専用の認証情報欄を使用してください。",
  "Settings sync excludes conversations, messages, tool execution history, runtime or connection state, global approval mode, and the enabled state, port, exposed-tool settings, and access token of Termind’s built-in MCP server. That token is stored only in the Data Protection Keychain on the current Mac. Enabling sync does not automatically connect to MCP servers or execute tools. Apple processes synced data; Termind does not operate a backend that receives this configuration.": "設定の同期には、会話、メッセージ、ツール実行履歴、実行時や接続の状態、全体の承認モード、Termind内蔵MCPサーバーの有効状態・ポート・公開ツール設定・アクセストークンは含まれません。このトークンは現在のMacのデータ保護キーチェーンにのみ保存されます。同期を有効にしても、MCPサーバーへの接続やツール実行が自動で行われることはありません。同期データはAppleが処理し、Termindはこれらの設定を受信するバックエンドを運営していません。",
  "Passwords and private keys": "パスワードと秘密鍵",
  "Passwords, software SSH private keys, AI API keys, and MCP credentials are stored in Apple’s Data Protection Keychain, not in the Vault database. You can choose whether to save a software SSH key’s passphrase with its private key in Keychain; if you do not, Termind asks for it when connecting. Storage options for passwords and SSH keys include:": "パスワード、ソフトウェアSSH秘密鍵、AI APIキー、MCP認証情報は、Vaultデータベースではなく、Appleのデータ保護キーチェーンに保存されます。ソフトウェアSSH鍵のパスフレーズを秘密鍵と一緒にキーチェーンへ保存するかどうかは選択できます。保存しない場合は接続時に入力を求めます。パスワードとSSH鍵の保存方法は次のとおりです。",
  "the Keychain item may sync across your devices through iCloud Keychain.": "キーチェーン項目は、iCloudキーチェーンを通じてデバイス間で同期される場合があります。",
  "This Device": "このデバイス",
  "the item is marked for this device only and does not sync.": "このデバイス専用として保存され、同期されません。",
  "Secure Enclave": "Secure Enclave",
  "the private key is non-exportable and does not sync to other devices.": "秘密鍵はエクスポートできず、他のデバイスにも同期されません。",
  "For a compatible FIDO2 hardware key, the Vault stores a credential reference and public key, which may sync with Vault data. The private key stays on the hardware key and is needed to authenticate even if its reference syncs.": "対応するFIDO2ハードウェアキーでは、Vaultに認証情報への参照と公開鍵を保存します。これらはVaultデータと同期できますが、秘密鍵はハードウェアキー内に残ります。参照が同期されても、認証にはハードウェアキーが必要です。",
  "When you first enable settings sync, existing AI API keys and remote MCP client bearer tokens migrate from local Keychain storage to iCloud Keychain; configuration records contain only references to these credentials. Failed migrations retain the local copy and can be retried. The built-in MCP server token is excluded; copies synchronized by older releases are moved to and verified in the local Keychain before being removed from iCloud Keychain. Credentials that have never been enabled for sync remain local. Turning off settings sync leaves migrated AI and remote MCP credentials managed by iCloud Keychain, where subsequent changes may still sync. Your Apple account and system settings determine whether iCloud Keychain is enabled, which devices receive items, and how Apple protects them. Configuration and credentials may reach another device at different times.": "設定の同期を初めて有効にすると、既存のAI APIキーとリモートMCPクライアントのBearerトークンを、ローカルキーチェーンからiCloudキーチェーンへ移行します。設定レコードには認証情報への参照のみが含まれます。移行に失敗した場合はローカルのコピーを保持し、再試行できます。内蔵MCPサーバーのトークンは対象外です。旧バージョンで同期されたコピーは、ローカルキーチェーンへの移動と検証を行った後、iCloudキーチェーンから削除します。一度も同期を有効にしていない認証情報はローカルに残ります。設定の同期をオフにしても、移行済みのAIおよびリモートMCP認証情報はiCloudキーチェーンの管理下にあり、以後の変更も同期される場合があります。iCloudキーチェーンの有効状態、受信するデバイス、Appleによる保護方法は、Appleアカウントとシステム設定によって決まります。設定と認証情報が別のデバイスに届くタイミングは異なる場合があります。",
  "Termind uses Apple StoreKit to verify the annual Pro subscription, introductory free trial, lifetime purchase, restored purchases, revocations, renewal state, and Family Sharing access. Apple processes purchase-account, transaction, and payment information under its policies. Termind does not receive your complete payment details.": "TermindはApple StoreKitを使い、Pro年間サブスクリプション、初回無料トライアル、買い切り購入、購入の復元、取り消し、更新状態、ファミリー共有の利用資格を検証します。購入アカウント、取引、支払いに関する情報は、Appleが同社のポリシーに従って処理します。Termindが完全な支払い情報を受け取ることはありません。",
  "RevenueCat provides our purchase validation, entitlement synchronization, and paywall service. Its SDK sends a randomly generated anonymous app user ID, purchase and subscription records, and app/device environment information needed to provide these services. Restoring the same Apple purchase can associate your anonymous IDs across devices. We do not send RevenueCat your host credentials, terminal content, conversations, AI API keys, or payment-card details, and automatic device-identifier collection is disabled.": "RevenueCatは、購入検証、利用権限の同期、ペイウォールのサービスを提供します。SDKは、無作為に生成した匿名アプリユーザーID、購入・サブスクリプションの記録、サービス提供に必要なアプリとデバイスの環境情報を送信します。同じAppleでの購入を復元すると、デバイス間の匿名IDが関連付けられる場合があります。ホストの認証情報、ターミナル内容、会話、AI APIキー、決済カード情報はRevenueCatへ送信しません。デバイス識別子の自動収集も無効にしています。",
  "Free-trial eligibility, duration, and subscription expiration are based on the store's product and purchase records. Termind does not use device fingerprinting or operate its own license server.": "無料トライアルの対象資格と期間、サブスクリプションの有効期限は、ストアの商品情報と購入記録に基づきます。Termindはデバイスのフィンガープリントを使用せず、独自のライセンスサーバーも運営していません。",
  "RevenueCat Privacy Policy": "RevenueCatのプライバシーポリシー",
  "AI providers and MCP": "AIプロバイダーとMCP",
  "AI features are optional and use a bring-your-own-key model. You may configure any endpoint that speaks the Chat Completions, Responses, Messages, or generateContent protocol. When you use AI, Termind sends the data needed for the request directly to the selected endpoint, which may include:": "AI機能は任意で、自分のキーを使う方式です。Chat Completions、Responses、Messages、generateContentのいずれかのプロトコルに対応するエンドポイントを設定できます。AIを使うと、Termindはリクエストに必要なデータを選択したエンドポイントへ直接送信します。次の情報が含まれる場合があります。",
  "your prompts, conversation history, selected images, and attachments;": "プロンプト、会話履歴、選択した画像、添付ファイル。",
  "current session context, such as host and remote-system information and working directory;": "ホストやリモートシステムの情報、作業ディレクトリなど、現在のセッションのコンテキスト。",
  "tool names, arguments, results, and command output or file contents you authorize the agent to read;": "ツール名、引数、結果、およびエージェントによる読み取りを許可したコマンド出力やファイル内容。",
  "the API key or access token used to authenticate the request.": "リクエストの認証に使うAPIキーまたはアクセストークン。",
  "Private-key material is not sent to the model as chat context. Termind resolves credentials locally to establish SSH connections. Review the privacy policy, retention controls, and enterprise terms of your selected AI provider. The operator of a custom endpoint is responsible for that endpoint.": "秘密鍵の内容をチャットのコンテキストとしてモデルに送信することはありません。TermindはSSH接続の確立に必要な認証情報をローカルで取得します。選択したAIプロバイダーのプライバシーポリシー、保持期間の設定、企業向け規約をご確認ください。カスタムエンドポイントについては、その運営者が責任を負います。",
  "If you add a remote MCP server, Termind exchanges requests, tool arguments, and results according to the tools that server exposes. The data shared depends on the server you enable and tools you invoke. On Mac only, Termind’s built-in MCP server listens on the local loopback interface by default; if you change how it is exposed, you are responsible for securing access.": "リモートMCPサーバーを追加すると、Termindはそのサーバーが公開するツールに従って、リクエスト、ツールの引数、結果をやり取りします。共有されるデータは、有効にしたサーバーと呼び出すツールによって異なります。Mac専用の内蔵MCPサーバーは、既定ではローカルのループバックインターフェイスで待ち受けます。公開方法を変更する場合、アクセスの安全性はユーザーが確保する必要があります。",
  "Web Search is optional and can be disabled in Settings at any time. When the selected AI model does not use provider-native search, Termind performs a local Web Search from the current device, queries the following search engines, and visits selected result pages to extract readable content:": "ウェブ検索は任意で、設定からいつでも無効にできます。選択したAIモデルがプロバイダー内蔵の検索を使わない場合、Termindは現在のデバイスからウェブ検索を実行し、次の検索エンジンに問い合わせ、選択した結果ページを訪れて読みやすい内容を抽出します。",
  "Query and standard network-request information": "検索クエリと通常のネットワークリクエスト情報",
  "Requests go directly from the current device to these search engines and selected result websites, so they will generally also receive your IP address, user agent, requested URL, and other standard network-request information. Result-page titles, URLs, and bounded Markdown content are sent to your selected AI provider as tool results.": "リクエストは現在のデバイスから検索エンジンと選択した結果のウェブサイトへ直接送信されるため、通常、相手にはIPアドレス、ユーザーエージェント、リクエストURLなどの標準的なネットワーク情報も届きます。結果ページのタイトル、URL、上限を設けたMarkdownコンテンツは、ツールの結果として選択したAIプロバイダーへ送信されます。",
  "Some AI models support provider-native search. When enabled, the AI provider performs the search on its own servers, and that provider—not Termind's local Web Search and the search engines above—processes the query and search activity.": "一部のAIモデルはプロバイダー内蔵の検索に対応しています。有効にすると、AIプロバイダーが自社サーバーで検索し、クエリと検索活動を処理します。この場合、Termindのローカルウェブ検索や上記の検索エンジンは使用しません。",
  "SSH, SFTP, web fetches, and remote actions": "SSH、SFTP、ウェブ取得、リモート操作",
  "When you connect to a host, Termind sends the information required to establish the connection to that host and any proxy or jump host you configure. Passwords are used for authentication inside the encrypted SSH session. SSH private keys remain on the current device and are used to sign locally. Target systems may log IP addresses, usernames, times, commands, file transfers, and other activity according to their own configuration.": "ホストへ接続すると、Termindは接続の確立に必要な情報を、そのホストと設定済みのプロキシまたは踏み台ホストへ送信します。パスワードは暗号化されたSSHセッション内での認証に使います。SSH秘密鍵は現在のデバイスに残り、ローカルで署名に使われます。接続先のシステムは、その設定に応じてIPアドレス、ユーザー名、日時、コマンド、ファイル転送、その他の活動を記録する場合があります。",
  "When you or the agent fetches a web page, Termind directly visits the specified HTTP(S) address, including private-network addresses. The destination generally receives your IP address, URL, user agent, and standard network-request information. Depending on the tool call, bounded Markdown or original HTML may be sent to your selected AI provider as context. Termind cannot control the destination’s logging or privacy practices.": "ユーザーまたはエージェントがウェブページを取得すると、Termindは指定したHTTP(S)アドレスへ直接アクセスします。プライベートネットワークのアドレスも含まれます。通常、接続先にはIPアドレス、URL、ユーザーエージェント、標準的なネットワークリクエスト情報が届きます。ツール呼び出しによっては、上限を設けたMarkdownまたは元のHTMLをコンテキストとして選択したAIプロバイダーへ送信します。Termindは接続先のログ記録やプライバシー慣行を管理できません。",
  "Sign-in and device information": "ログインとデバイス情報",
  "Tailscale is optional. When you sign in from a host group, Termind registers an embedded node with Tailscale or the control service you configure. Browser sign-in is handled by that service and its identity provider. If you use an Auth Key, it is sent to the selected control service to authorize the node; it is not included in synced group configuration.": "Tailscaleは任意です。ホストグループからログインすると、TermindはTailscaleまたは設定したコントロールサービスに組み込みノードを登録します。ブラウザでのログインは、そのサービスとIDプロバイダーが処理します。Auth Keyを使う場合は、ノードの承認のため選択したコントロールサービスへ送信します。同期されるグループ設定には含めません。",
  "The control service receives information needed to authenticate the node and coordinate connections, including the device name you configure, operating system, Tailscale version, IP addresses, node identifiers, and public keys. It supplies the peer information Termind uses to show devices and verify Tailscale SSH host keys. Tailnet administrators can see device and connection information according to their permissions and logging settings.": "コントロールサービスは、ノードの認証と接続の調整に必要な情報を受け取ります。設定したデバイス名、OS、Tailscaleのバージョン、IPアドレス、ノード識別子、公開鍵などが含まれます。また、Termindがデバイスの表示とTailscale SSHホスト鍵の検証に使うピア情報を提供します。Tailnet管理者は、権限とログ設定に応じてデバイスや接続の情報を確認できます。",
  "Traffic, relays, and exit nodes": "通信、リレー、Exit Node",
  "Traffic between Tailscale nodes is encrypted with WireGuard. Connections may be direct or pass through a peer relay or DERP relay, which forwards encrypted traffic without decrypting its contents. The services involved can process connection metadata such as IP addresses, connection times, and traffic volume; Tailscale may also process diagnostic and connection logs under its own policy. This processing is separate from Termind’s optional Crashlytics reporting.": "Tailscaleノード間の通信はWireGuardで暗号化されます。接続は直接、またはピアリレーやDERPリレーを経由する場合があります。リレーは内容を復号せずに暗号化された通信を中継します。関係するサービスは、IPアドレス、接続日時、通信量などの接続メタデータを処理できます。Tailscaleも同社のポリシーに従って診断ログや接続ログを処理する場合があります。これはTermindの任意のCrashlyticsレポートとは別の処理です。",
  "If you select an Exit Node, traffic routed through it is handled by its operator, who may see destinations and any contents not protected by application-layer encryption. SSH and SFTP remain encrypted to the target server. DNS resolvers may process the names queried according to your network configuration. Termind’s embedded connection does not turn on a system-wide VPN or route other apps’ traffic.": "Exit Nodeを選択すると、それを経由する通信は運営者によって処理されます。運営者は、接続先やアプリケーション層で暗号化されていない内容を確認できる場合があります。SSHとSFTPは対象サーバーまで暗号化されたままです。DNSリゾルバーはネットワーク設定に従って問い合わせ名を処理する場合があります。Termind内の接続は、システム全体のVPNを有効にしたり、他のアプリの通信を経由させたりしません。",
  "Local storage and iCloud": "ローカル保存とiCloud",
  "Private node state, including the keys used to maintain the Tailnet identity, is stored in Apple Keychain items marked for this device only, with Keychain synchronization disabled. The app stores the local profile reference and discovered peer cache on this device. These are not included in Termind’s iCloud sync, so another device must sign in separately.": "TailnetのIDを維持する鍵を含む非公開のノード状態は、このデバイス専用かつ同期無効のAppleキーチェーン項目に保存します。ローカルプロファイルへの参照と検出したピアのキャッシュも、このデバイスに保存します。TermindのiCloud同期には含まれないため、別のデバイスでは個別にログインが必要です。",
  "With Vault sync enabled, the group’s control-service URL, Tailnet DNS suffix, selected Exit Node identifier, and saved host preferences can sync through your private iCloud database. Host preferences include usernames, tags, colors, detected distribution, character encoding, initial SFTP path, shell-integration choice, startup-snippet reference, and environment variables. Do not put secrets in these configuration fields.": "Vaultの同期を有効にすると、グループのコントロールサービスURL、Tailnet DNSサフィックス、選択したExit Nodeの識別子、保存したホスト設定をプライベートiCloudデータベース経由で同期できます。ホスト設定には、ユーザー名、タグ、色、検出したディストリビューション、文字コード、SFTPの初期パス、シェル統合の選択、起動時スニペットへの参照、環境変数が含まれます。これらの設定欄に秘密情報を入力しないでください。",
  "Tailscale’s processing and retention are governed by its Privacy Policy. If you use a custom control service, its operator’s policy also applies. Data retained by a Tailnet administrator, identity provider, relay, DNS resolver, or Exit Node operator is subject to that party’s policies.": "Tailscaleによる処理と保持は、同社のプライバシーポリシーに従います。カスタムコントロールサービスを使う場合は、運営者のポリシーも適用されます。Tailnet管理者、IDプロバイダー、リレー、DNSリゾルバー、Exit Node運営者が保持するデータは、それぞれのポリシーに従います。",
  "Tailscale Privacy Policy": "Tailscaleのプライバシーポリシー",
  "Camera attachments and speech transcription": "カメラ添付と音声文字起こし",
  "Camera attachments on iPhone and iPad": "iPhoneとiPadのカメラ添付",
  "Termind accesses the camera only after you choose Camera in the Assistant and grant permission. A photo remains in the conversation draft until you send it; when sent, it is handled as described in the AI section. Mac does not expose this camera attachment flow.": "Termindがカメラにアクセスするのは、アシスタントで「カメラ」を選択し、許可した後だけです。写真は送信するまで会話の下書きに残り、送信するとAIの項で説明したとおりに扱われます。Macにはこのカメラ添付機能はありません。",
  "Speech transcription": "音声文字起こし",
  "Termind captures audio only after you press the transcription button and grant microphone and Speech Recognition permissions. Transcription uses Apple Speech. Depending on operating-system settings, language, and device capabilities, Apple may process audio on-device or on its servers. Termind stops the active recording after completion, cancellation, or failure. Transcribed text enters your chat draft and, if sent, is handled as described in the AI section.": "Termindが音声を録音するのは、文字起こしボタンを押し、マイクと音声認識の権限を許可した後だけです。文字起こしにはApple Speechを使います。OSの設定、言語、デバイスの機能に応じて、Appleがデバイス上または同社サーバーで音声を処理する場合があります。完了、キャンセル、失敗すると録音を停止します。文字起こししたテキストはチャットの下書きに入り、送信した場合はAIの項で説明したとおりに扱われます。",
  "Termind asks for your choice before enabling Google Firebase Crashlytics. If you agree, diagnostic data is sent to Google to help us diagnose and fix problems. This includes crash stack traces, relevant application state, app and operating-system versions, device information, and diagnostic installation identifiers. Termind does not attach terminal output, chat content, passwords, private keys, or a user account ID.": "TermindはGoogle Firebase Crashlyticsを有効にする前に、共有するかどうかを確認します。同意すると、問題の診断と修正のため、診断データをGoogleへ送信します。これにはクラッシュのスタックトレース、関連するアプリ状態、アプリとOSのバージョン、デバイス情報、診断用のインストール識別子が含まれます。ターミナル出力、チャット内容、パスワード、秘密鍵、ユーザーアカウントIDは添付しません。",
  "Your choice is stored only on this device and does not sync through iCloud. You can decline without losing app features, or change your choice in Settings > App > Diagnostics. Turning sharing off blocks future uploads; it does not withdraw data already sent or stop an upload already authorized. Restarting Termind stops local crash recording. If you opt back in, pending diagnostic data from before consent was restored is discarded.": "選択はこのデバイスにのみ保存され、iCloudでは同期されません。共有を拒否してもアプリの機能は制限されず、「設定」→「アプリ」→「診断」で変更できます。共有をオフにすると以後のアップロードを防ぎますが、送信済みのデータを撤回したり、承認済みのアップロードを停止したりはしません。Termindを再起動するとローカルのクラッシュ記録が停止します。再び共有を有効にした場合、再同意前から保留されていた診断データは破棄されます。",
  "Google processes this diagnostic data under the Firebase data-processing terms. For Firebase's data handling and retention information, see": "GoogleはFirebaseのデータ処理規約に従って診断データを処理します。Firebaseのデータの取り扱いと保持については、次をご覧ください。",
  "Firebase Privacy and Security": "Firebaseのプライバシーとセキュリティ",
  "This website sets no analytics cookies, uses no advertising technology, and contains no contact form. It stores only your selected site language in local browser storage; that preference is not transmitted to Termind. The hosting provider may still process standard server logs—such as IP address, request time, path, and user agent—to deliver the site, prevent abuse, and maintain security, subject to the hosting provider’s policy.": "このウェブサイトは、分析用Cookieや広告技術を使わず、お問い合わせフォームも設置していません。選択した表示言語だけをブラウザのローカルストレージに保存し、その設定をTermindへ送信することはありません。ホスティング提供者は、サイトの配信、不正利用の防止、セキュリティ維持のため、IPアドレス、リクエスト日時、パス、ユーザーエージェントなどの標準的なサーバーログを、同社のポリシーに従って処理する場合があります。",
  "Retention, deletion, and your controls": "保持、削除、ユーザーによる管理",
  "You can turn off the main iCloud Sync switch or deselect Vault, Metrics, or Settings to pause the corresponding configuration transfers. You can also disable Web Search, speech permissions, and other optional features. Pausing sync does not erase existing cloud data or stop iCloud Keychain sync for migrated AI credentials.": "iCloud同期全体のスイッチをオフにするか、Vault・メトリクス・設定の選択を外すことで、該当する設定の転送を一時停止できます。ウェブ検索、音声の権限、その他の任意機能も無効にできます。同期の一時停止は、既存のクラウドデータを削除せず、移行済みのAI認証情報のiCloudキーチェーン同期も停止しません。",
  "You can delete hosts, monitored items, credential references, conversations, and other content in the app. When the corresponding sync is enabled, Vault, Metrics, and settings deletions propagate to iCloud; deletions made while paused or offline propagate after sync resumes. The protocol retains necessary deletion markers to prevent deleted content from returning, so deletion does not immediately erase all sync metadata.": "アプリ内でホスト、監視項目、認証情報への参照、会話などを削除できます。該当する同期が有効なら、Vault、メトリクス、設定の削除はiCloudにも反映されます。一時停止中やオフラインで行った削除は、同期再開後に反映されます。削除した内容が復活しないよう、プロトコルは必要な削除マーカーを保持するため、削除しても同期メタデータがすべて直ちに消えるわけではありません。",
  "Uninstalling the app may not automatically delete data in Keychain or iCloud. Delete relevant credentials, Vault data, and settings in the app before uninstalling, or use Apple’s system settings to manage iCloud and Keychain.": "アプリをアンインストールしても、キーチェーンやiCloudのデータが自動で削除されるとは限りません。アンインストール前にアプリ内で関連する認証情報、Vaultデータ、設定を削除するか、Appleのシステム設定からiCloudとキーチェーンを管理してください。",
  "To remove a Tailnet sign-in from this device, log out in the group editor and save the change. Termind removes the local profile reference and peer cache, closes the node, and schedules its private Keychain state and supporting files for deletion, retrying if cleanup fails. Group configuration and synced preferences are separate; delete the group if you also want to remove them. Local logout does not erase provider or administrator logs or revoke a reusable Auth Key. Manage device removal and key revocation through the control service.": "このデバイスからTailnetのログインを削除するには、グループ編集画面でログアウトし、変更を保存します。Termindはローカルプロファイルへの参照とピアキャッシュを削除し、ノードを閉じ、非公開のキーチェーン状態と関連ファイルの削除を予定します。クリーンアップに失敗した場合は再試行します。グループ設定と同期済みの設定は別なので、それらも削除したい場合はグループを削除してください。ローカルでのログアウトは、提供者や管理者のログを消したり、再利用可能なAuth Keyを失効させたりしません。デバイスの削除と鍵の失効はコントロールサービスで管理してください。",
  "Data retained by AI or search providers, Apple, Tailscale or a custom control service, or remote hosts must be managed through those providers. The Termind developer cannot delete data from those services on your behalf.": "AIや検索の提供者、Apple、Tailscaleまたはカスタムコントロールサービス、リモートホストが保持するデータは、各提供者を通じて管理する必要があります。Termindの開発者が代わりにこれらのサービスのデータを削除することはできません。",
  "Termind is not directed to children under 13, and we do not knowingly collect children’s personal information.": "Termindは13歳未満のお子様を対象としておらず、お子様の個人情報を意図的に収集することはありません。",
  "Changes and contact": "変更とお問い合わせ",
  "If the product’s data practices materially change, we will update the version and effective date on this page and provide notice in the app where appropriate.": "製品のデータ取り扱いに重要な変更が生じた場合は、このページのバージョンと施行日を更新し、必要に応じてアプリ内でも通知します。",
  "For privacy questions, email privacy-termind@akinokaede.com. For product and technical support questions, email support-termind@akinokaede.com. For business inquiries, email termind@akinokaede.com. Do not include passwords, private keys, API keys, complete host addresses, unredacted logs, or other unnecessary sensitive information.": "プライバシーに関するご質問はprivacy-termind@akinokaede.com、製品・技術サポートはsupport-termind@akinokaede.com、ビジネスのお問い合わせはtermind@akinokaede.comへご連絡ください。パスワード、秘密鍵、APIキー、完全なホストアドレス、未加工のログなど、不要な機密情報は含めないでください。",
  "Privacy questions": "プライバシーに関するご質問",
  "Product & technical support": "製品・技術サポート",
  "Business inquiries": "ビジネスのお問い合わせ",
  "Termind Support": "Termindサポート",
  "Need a hand?": "お困りですか？",
  "Tell us what went wrong. We’ll help you get connected and back to your work.": "どんな問題が起きたかお知らせください。接続を復旧し、作業に戻れるようお手伝いします。",
  "Email support": "メールで問い合わせる",
  "What to include": "ご連絡いただきたい内容",
  "What happened": "起きたこと",
  "Describe the action, expected result, and what happened instead.": "行った操作、期待した結果、実際に起きたことを説明してください。",
  "Your setup": "ご利用環境",
  "Include the Termind version, device model, operating-system version, and affected feature.": "Termindのバージョン、デバイスのモデル、OSのバージョン、問題のある機能をお知らせください。",
  "Redacted clues": "機密情報を除いた手がかり",
  "Screenshots and errors help, after sensitive details are removed.": "機密情報を取り除いたスクリーンショットやエラー内容が、解決の手がかりになります。",
  "Redact before you send": "送信前に機密情報を削除",
  "Never send passwords, private keys, API keys, complete host addresses, access tokens, or unreviewed logs. We will not ask for them by email.": "パスワード、秘密鍵、APIキー、完全なホストアドレス、アクセストークン、未確認のログは送らないでください。メールでこれらを求めることはありません。",
  "Privacy matters": "プライバシーについて",
  "Questions about your data": "データに関するご質問",
  "For questions about the privacy policy, data sync, or third-party services, contact us through the privacy address.": "プライバシーポリシー、データ同期、第三者サービスについては、プライバシー専用のメールアドレスへご連絡ください。",
  "Quick checks": "まずは確認",
  "Before you write": "お問い合わせの前に",
  "Confirm the relevant feature is enabled in Settings.": "該当する機能が設定で有効になっているか確認してください。",
  "Check this device’s network, iCloud, Keychain, and permission status.": "このデバイスのネットワーク、iCloud、キーチェーン、権限の状態を確認してください。",
  "Retry once and note the exact steps that reproduce the issue.": "一度再試行し、問題を再現する正確な手順を記録してください。",
  "SSH, Telnet, SFTP, and terminal uploads": "SSH、Telnet、SFTP、ターミナルからのアップロード",
  "Snippets and port forwarding": "スニペットとポート転送",
  "AI Command Generator with your own key": "自分のキーで使えるAIコマンド生成",
  "Monitor up to 3 servers": "最大3台のサーバーを監視",
  "On macOS: serial, multi-pane workspaces, and input broadcasting": "macOSではシリアル接続、マルチペイン、一括入力にも対応",
  "Parallel SFTP": "並列SFTP転送",
  "Transfer across multiple SSH connections, with smart scheduling and global and per-host concurrency limits.": "複数のSSH接続で転送。状況に応じたスケジュール制御と、全体・ホストごとの同時実行数の上限を設定できます。",
  "Multi-connection port forwarding": "複数接続のポート転送",
  "On macOS, spread local and dynamic forwarding traffic across an SSH connection pool.": "macOSで、ローカル転送とダイナミック転送の通信を複数のSSH接続に分散します。",
  "Built-in Tailscale": "Tailscaleを内蔵",
  "Sign in to multiple tailnets, discover devices, and connect through Tailscale SSH without a separate client on this device.": "複数のTailnetにログインし、デバイスを検出してTailscale SSHで接続。このデバイスに別のクライアントを入れる必要はありません。",
  "AI Assistant": "AIアシスタント",
  "Investigate issues, run commands, and work with files using your model and permissions, plus skills and optional local memory.": "自分のモデルと権限設定で、問題の調査、コマンド実行、ファイル操作を支援。スキルや任意のローカル記憶も使えます。",
  "More servers to monitor": "さらに多くのサーバーを監視",
  "Go beyond the free limit of 3 monitored servers and keep their live metrics in one workspace.": "無料の3台を超えて監視し、リアルタイムのメトリクスをひとつのワークスペースで確認できます。",
  "iCloud sync": "iCloud同期",
  "Sync Vault, monitoring configuration, and settings. Credentials use iCloud Keychain; chats and memory stay local.": "Vault、監視設定、各種設定を同期。認証情報にはiCloudキーチェーンを使い、チャットと記憶はローカルに残ります。",
  "MCP connections": "MCP接続",
  "Connect remote MCP tools to the Assistant. On macOS, the built-in MCP server also lets compatible AI clients use your SSH and SFTP tools.": "リモートMCPツールをアシスタントに接続。macOSの内蔵MCPサーバーを使えば、対応するAIクライアントからSSHやSFTPツールも利用できます。",
  "Annual": "年間プラン",
  "/ year": "/年",
  "A year of your complete workspace.": "充実したワークスペースを、1年間。",
  "Billed annually. Renews until canceled.": "年額で請求。解約するまで自動更新されます。",
  "Every Pro feature": "すべてのPro機能",
  "macOS & iOS": "macOSとiOS",
  "Family Sharing included": "ファミリー共有に対応",
  "Cancel the next renewal at any time": "次回の更新はいつでもキャンセル可能",
  "Lifetime": "買い切り",
  "once": "1回のみ",
  "Your workspace, yours to keep.": "ずっと使える、あなたのワークスペース。",
  "One payment. No subscription renewal.": "お支払いは1回だけ。サブスクリプションの更新はありません。",
  "Lifetime Pro access": "Proを期限なく利用",
  "PRICING": "料金",
  "Start free.": "無料ではじめる。",
  "Make it yours.": "自分らしく使う。",
  "The essentials are free. Add Pro for a year or keep it for life. One purchase works on macOS and iOS, with Family Sharing included.": "基本機能は無料。Proは年間プランか買い切りで。1回の購入でmacOSとiOSに対応し、ファミリー共有も使えます。",
  "Free and Pro plans": "無料プランとProプラン",
  "Free": "無料",
  "Everything you need to get connected.": "接続に必要な機能を、ひと通り。",
  "forever": "ずっと無料",
  "No Termind account needed.": "Termindアカウントは不要です。",
  "Download free": "無料でダウンロード",
  "View on the App Store": "App Storeで見る",
  "Everything in Free, plus:": "無料プランの全機能に加えて：",
  "Explore all Pro features": "Proの全機能を見る",
  "Regional prices and available offers are shown in the App Store. Download Termind, then choose Pro in the app.": "地域ごとの価格と利用可能なオファーはApp Storeに表示されます。Termindをダウンロードし、アプリ内でProをお選びください。",
  "AI uses your own API key. Model provider usage is billed separately and is not included in either Pro plan.": "AIには自分のAPIキーを使います。モデルプロバイダーの利用料は別途請求され、どちらのProプランにも含まれません。",
  "ONE PRO. TWO WAYS TO OWN IT.": "ひとつのPRO。選べる2つのプラン。",
  "More room to do your work.": "もっと自由に、作業を進める。",
  "Annual and lifetime unlock the same Pro features.": "年間プランも買い切りも、使えるPro機能は同じです。",
  "Built-in Tailscale requires Tailscale SSH on the target server and access allowed by your Tailnet policy.": "内蔵Tailscaleの利用には、接続先でTailscale SSHが有効で、Tailnetポリシーによるアクセス許可が必要です。",
  "A few questions before you choose?": "プラン選びで、気になることは？",
  "Learn about features, sync, and how AI works in Termind.": "機能、同期、TermindのAIの仕組みについてご案内します。",
  "Read the FAQ": "よくある質問を見る",
  "Compare with Termius": "Termiusと比較",
  "Before you connect": "接続する前に",
  "Good to know.": "知っておきたいこと。",
  "What AI can do, how Tailscale connects, what Pro adds, and where your data goes.": "AIにできること、Tailscaleの接続方法、Proの機能、データの行き先について。",
  "Still wondering?": "まだ気になることがあれば。",
  "We’re here to help.": "お手伝いします。",
  "Go to Support": "サポートへ",
  "All comparisons": "すべての比較",
  "Compare the details": "詳しく比較",
  "Which one fits your workflow?": "あなたの作業に合うのは？",
  "CHOOSE TERMIND IF YOU NEED": "こんな使い方にはTERMIND",
  "The details that matter.": "大切な違いを、詳しく。",
  "Updated: ": "更新日：",
  "MAKE IT YOUR WORKSPACE": "あなたのワークスペースに",
  "Try Termind for yourself.": "Termindを試してみませんか。",
  "Start with free SSH, SFTP, and port forwarding. No Termind account needed.": "無料のSSH、SFTP、ポート転送から。Termindアカウントは不要です。",
  "Security is not": "セキュリティは、",
  "a single feature.": "ひとつの機能ではありません。",
  "Termind protects the whole path to your server: software credentials are kept in Apple’s security system, sensitive memory is zeroized after use, server identity is verified before authentication, and Assistant and MCP access stays within boundaries you choose.": "Termindはサーバーへ至る経路全体を保護します。ソフトウェアの認証情報はAppleのセキュリティ基盤に保存し、機密情報を含むメモリは使用後にゼロ化。認証前にサーバーの身元を検証し、アシスタントとMCPのアクセスはあなたが選んだ範囲に制限します。",
  "Explore the security model": "セキュリティモデルを見る",
  "Read the Privacy Policy": "プライバシーポリシーを読む",
  "A private key protected inside your device": "デバイス内で保護された秘密鍵",
  "PROTECTED": "保護されています",
  "Credentials · Connections · Actions": "認証情報 · 接続 · 操作",
  "Termind security principles": "Termindのセキュリティ原則",
  "Credentials are protected": "認証情報を保護",
  "Secure at rest, short-lived and zeroized in memory.": "保存時は安全に。メモリ内では短時間だけ保持し、使用後にゼロ化します。",
  "Trust is verified": "信頼を検証",
  "A changed server key is surfaced, not silently accepted.": "サーバー鍵の変更を通知し、無断では受け入れません。",
  "Access is your choice": "アクセスはあなたが選択",
  "Assistant and MCP features are optional and configurable.": "アシスタントとMCPは任意で、設定を調整できます。",
  "A short path": "メモリを通る時間も、",
  "through memory.": "できるだけ短く。",
  "A secret has to enter memory briefly for software-key authentication. Termind deliberately limits that window instead of letting plaintext linger in ordinary application values.": "ソフトウェア鍵による認証では、秘密情報を一時的にメモリへ読み込む必要があります。Termindは平文を通常のアプリ変数に残さず、その保持時間を意図的に制限します。",
  "SECRET MEMORY LIFECYCLE": "機密メモリのライフサイクル",
  "A secret passes through.": "秘密情報は通過する。",
  "Its trace does not.": "その痕跡は残さない。",
  "Normal memory release does not guarantee that old bytes disappear immediately. Termind therefore gives SSH passwords, software private keys, and passphrases a dedicated one-shot lifetime. The source buffer is cleared after the secret is moved, and the owned allocation is overwritten before it is released.": "通常のメモリ解放だけでは、古いバイト列が直ちに消える保証はありません。そのためTermindでは、SSHパスワード、ソフトウェア秘密鍵、パスフレーズに、1回限りの専用の有効期間を設けています。秘密情報の移動後に元のバッファを消去し、所有するメモリ領域を解放前に上書きします。",
  "Secret memory lifecycle": "機密メモリのライフサイクル",
  "Read when needed": "必要なときに読み込む",
  "Apple Keychain": "Appleキーチェーン",
  "Move once": "一度だけ移動",
  "Source cleared": "元の領域を消去",
  "Authenticate": "認証",
  "One-shot use": "1回限りの使用",
  "Overwrite": "上書き",
  "Then release": "その後に解放",
  "Cleanup is not a success-only path.": "成功したときだけ、消すのではありません。",
  "The same zeroization runs when authentication fails or exits early. Consuming or clearing the shared one-shot backing also invalidates Termind’s other references to that secret.": "認証に失敗した場合や途中で終了した場合も、同じゼロ化処理を行います。共有する1回限りの保存領域を使用または消去すると、Termind内の同じ秘密情報への他の参照も無効になります。",
  "AT REST": "保存時の保護",
  "Protected before it enters memory.": "メモリに入る前から、安全に。",
  "Termind keeps host details and software credentials in separate places. Passwords and software private keys live in Apple’s Data Protection Keychain, while the Vault stores the information needed to identify and organize them. You can choose whether to save a software key’s passphrase with that key; otherwise, enter it when connecting.": "Termindはホスト情報とソフトウェア認証情報を別々に保存します。パスワードとソフトウェア秘密鍵はAppleのデータ保護キーチェーンに置き、Vaultには識別と整理に必要な情報を保存します。ソフトウェア鍵のパスフレーズを一緒に保存するかどうかは選択でき、保存しない場合は接続時に入力します。",
  "Keep a password or software SSH key on the current device only. It does not sync to your other devices.": "パスワードやソフトウェアSSH鍵を現在のデバイスだけに保存。他のデバイスには同期しません。",
  "DEVICE ONLY": "このデバイスのみ",
  "iCloud Keychain": "iCloudキーチェーン",
  "Let Apple’s iCloud Keychain make a password or software SSH key available across your approved devices.": "AppleのiCloudキーチェーンを使い、承認済みのデバイス間でパスワードやソフトウェアSSH鍵を利用できます。",
  "YOUR APPLE DEVICES": "あなたのAPPLEデバイス",
  "Generate a hardware-protected P-256 key whose private half cannot be exported or synced. You can also require Touch ID or the device password when it is used.": "エクスポートも同期もできない、ハードウェアで保護されたP-256秘密鍵を生成。使用時にTouch IDやデバイスのパスワードを要求することもできます。",
  "NON-EXPORTABLE": "エクスポート不可",
  "Hardware Keys": "ハードウェアキー",
  "Use a compatible FIDO2 hardware key for ECDSA-SK P-256 SSH authentication. The private key stays on the hardware key.": "対応するFIDO2ハードウェアキーでECDSA-SK P-256のSSH認証を利用。秘密鍵はハードウェアキー内に残ります。",
  "HARDWARE KEYS": "ハードウェアキー",
  "BEFORE CREDENTIALS ARE USED": "認証情報を使う前に",
  "The server proves its identity first.": "まず、サーバーの身元を確認。",
  "Known Hosts records the server’s public-key fingerprint. On a first connection, Termind asks you to review it. If the key later changes, Termind stops and shows the mismatch so you can investigate instead of quietly continuing.": "既知のホストには、サーバー公開鍵のフィンガープリントを記録します。初回接続時にTermindが確認を求め、後で鍵が変わった場合は接続を止めて不一致を表示します。黙って接続を続けず、原因を調べられるようにします。",
  "02 / ASSISTANT": "02 / アシスタント",
  "Useful access.": "役立つアクセス。",
  "Visible boundaries.": "見える権限の境界。",
  "The AI Assistant is optional and uses the model provider you configure. SSH authentication happens locally: private-key material is not placed into the conversation or sent to the model as chat context.": "AIアシスタントは任意の機能で、設定したモデルプロバイダーを使います。SSH認証はローカルで行い、秘密鍵の内容を会話に含めたり、チャットのコンテキストとしてモデルへ送信したりしません。",
  "When the Assistant needs to run a command or work with a file, Termind applies the tool policy and approval mode you selected. You can review actions yourself, use a security-review model, or grant broader access when the environment calls for it.": "アシスタントがコマンド実行やファイル操作を必要とすると、Termindは選択したツールポリシーと承認モードを適用します。操作を自分で確認する、安全性を審査するモデルを使う、環境に応じてより広いアクセスを許可する、といった選択ができます。",
  "Know what is shared": "共有される情報を確認",
  "Prompts, authorized command output, file contents, attachments, and relevant session context may be sent to your selected model provider. Its policies govern that data. Choose permissions and a provider appropriate for the server you are working on.": "プロンプト、許可したコマンド出力、ファイル内容、添付ファイル、関連するセッションのコンテキストは、選択したモデルプロバイダーへ送信される場合があります。そのデータには提供者のポリシーが適用されます。作業対象のサーバーに適した権限とプロバイダーを選んでください。",
  "03 / BUILT-IN MCP SERVER": "03 / 内蔵MCPサーバー",
  "A local doorway.": "ローカルの入り口を、",
  "Opened by you.": "あなたが開く。",
  "On Mac, Termind’s built-in MCP server lets compatible local clients use the SSH and SFTP tools you choose to expose. It is off by default and listens only on this Mac’s loopback addresses.": "Macの内蔵MCPサーバーを使うと、対応するローカルクライアントから、公開したSSHとSFTPツールを利用できます。初期設定ではオフで、このMacのループバックアドレスのみで待ち受けます。",
  "Built-in MCP security layers": "内蔵MCPのセキュリティ層",
  "Off by default": "初期設定ではオフ",
  "Enable it when needed": "必要なときだけ有効に",
  "Local only": "ローカルのみ",
  "Bearer Token": "Bearerトークン",
  "Stored on this Mac": "このMacに保存",
  "Tool switches": "ツールごとのスイッチ",
  "Expose only what you need": "必要なツールだけ公開",
  "An authenticated MCP client can invoke the tools you expose without a confirmation prompt for every call. Give the Bearer Token only to clients you trust, expose the minimum tools they need, and turn the server off when it is not in use.": "認証済みのMCPクライアントは、公開したツールを、呼び出しごとの確認なしで実行できます。Bearerトークンは信頼できるクライアントにだけ渡し、必要最小限のツールを公開して、使わないときはサーバーをオフにしてください。",
  "SECURITY IS A SHARED PRACTICE": "セキュリティは、共に守るもの",
  "A secure foundation,": "安全な基盤と、",
  "with choices that stay yours.": "あなたが選べる自由。",
  "Prefer a Secure Enclave key when you do not need to move or export it—the private key never enters app memory.": "移動やエクスポートが不要なら、Secure Enclave鍵を優先してください。秘密鍵がアプリのメモリに入ることはありません。",
  "Verify a new or changed host fingerprint through a trusted channel.": "新しいホストや変更されたフィンガープリントは、信頼できる経路で確認してください。",
  "Give the Assistant and built-in MCP server only the access needed for the task.": "アシスタントと内蔵MCPサーバーには、作業に必要なアクセスだけを与えてください。",
  "Keep your Apple devices, accounts, and model-provider credentials protected.": "Appleデバイス、アカウント、モデルプロバイダーの認証情報を保護してください。",
  "COMPARE": "比較",
  "A closer look.": "違いを知って、",
  "A clearer choice.": "自分に合う選択を。",
  "Compare features, limits, and pricing to find the SSH tool that fits your workflow.": "機能、制限、価格を比較して、作業に合うSSHツールを見つけてください。",
  "Explore the comparisons": "比較を見る",
  "Comparison topics": "比較する項目",
  "Read comparison": "詳しく比較",
  "Getting to know Termind?": "Termindについてもっと知りたい方へ",
  "Start with the FAQ": "まずは、よくある質問から",
  "Privacy Policy — Termind": "プライバシーポリシー — Termind",
  "How Termind handles device data, iCloud and Keychain sync, Tailscale, AI providers, Web Search, remote connections, camera attachments, and speech transcription.": "デバイス上のデータ、iCloudとキーチェーンの同期、Tailscale、AIプロバイダー、ウェブ検索、リモート接続、カメラ添付、音声文字起こしに関するTermindのデータ取り扱い。",
  "Security by design — Termind": "設計から、安全に — Termind",
  "Learn how Termind protects SSH credentials at rest and in memory, verifies server identity, and keeps Assistant and MCP access within boundaries you control.": "SSH認証情報の保存時とメモリ内での保護、サーバーの身元確認、アシスタントとMCPのアクセス制御について紹介します。",
  "FAQ — Termind": "よくある質問 — Termind",
  "Get to know Termind’s AI Assistant, Hermes Memory, free and Pro features, supported devices, and how your data is stored and shared.": "TermindのAIアシスタント、Hermes Memory、無料・Pro機能、対応デバイス、データの保存と共有について。",
  "Pricing — Termind": "料金 — Termind",
  "Support — Termind": "サポート — Termind",
  "Get help with Termind for Mac, iPhone, and iPad.": "Mac、iPhone、iPad向けTermindのサポートをご案内します。",
  "Compare SSH clients — Termind": "SSHクライアントの比較 — Termind",
  "Compare Termind with Termius, WebSSH, ServerCat, and Prompt 3. Explore hardware keys, SSH workflows, monitoring, Tailscale, sync, and pricing.": "TermindをTermius、WebSSH、ServerCat、Prompt 3と比較。ハードウェアキー、SSHの作業、監視、Tailscale、同期、価格の違いを紹介します。",
  "SFTP transfers": "SFTP転送",
  "Transfer several files at once.": "複数のファイルを同時に転送。",
  "Free; multi-connection acceleration with Pro": "無料。Proで複数接続による高速化",
  "Parallel uploads and downloads with adjustable global and per-host limits. Pro adds multiple SSH connections and smart scheduling based on file size.": "アップロードとダウンロードを並行実行し、全体・ホストごとの上限を調整できます。Proでは複数のSSH接続と、ファイルサイズに応じたスケジュール制御も利用できます。",
  "Drag-and-drop terminal uploads": "ターミナルへのドラッグ＆ドロップ",
  "Drop a file into the terminal and keep working.": "ファイルをターミナルにドロップして、そのまま作業。",
  "Included for free": "無料で利用可能",
  "Drag local files into an SSH terminal to upload them without switching to the SFTP file browser.": "ローカルファイルをSSHターミナルにドラッグしてアップロード。SFTPブラウザへ切り替える必要はありません。",
  "Port forwarding": "ポート転送",
  "Reach remote services through SSH tunnels.": "SSHトンネルでリモートサービスにアクセス。",
  "Create multiple forwarding rules for free. On macOS, Pro spreads local and dynamic forwarding traffic across multiple SSH connections.": "複数の転送ルールを無料で設定。macOSのProでは、ローカル転送とダイナミック転送の通信を複数のSSH接続に分散できます。",
  "Connect to your private network from the app.": "アプリからプライベートネットワークに接続。",
  "In-app Tailnet access · Pro": "アプリ内でTailnetに接続 · Pro",
  "Sign in and sync Tailscale devices in host groups; each group can use a different Tailnet. No separate client or system VPN is needed. SSH and SFTP require Tailscale SSH on the server.": "ホストグループでTailscaleにログインし、デバイスを同期。グループごとに別のTailnetを使えます。別のクライアントやシステムVPNは不要です。SSHとSFTPの利用には、サーバー側でTailscale SSHが必要です。",
  "Built-in AI": "内蔵AI",
  "Generate commands or hand off a multi-step task.": "コマンドを生成したり、複数手順の作業を任せたり。",
  "Free command generation; Assistant with Pro": "コマンド生成は無料。アシスタントはPro",
  "Use your own model key. The Assistant runs commands and handles files within your chosen permissions, with skills, remote MCP tools, and optional local memory. Model usage is billed separately.": "自分のモデルキーを使用。アシスタントは選択した権限の範囲でコマンドやファイルを操作し、スキル、リモートMCPツール、任意のローカル記憶も使えます。モデルの利用料は別途かかります。",
  "External agents": "外部エージェント",
  "Connect your preferred AI client.": "好みのAIクライアントを接続。",
  "Built-in MCP server · Pro": "内蔵MCPサーバー · Pro",
  "On macOS, give clients such as Codex and Claude Code access to saved hosts, SSH commands, and SFTP files. Enable tools individually and review each call in the audit log.": "macOSでCodexやClaude Codeなどのクライアントに、保存済みホスト、SSHコマンド、SFTPファイルへのアクセスを提供。ツールを個別に有効にし、各呼び出しを監査ログで確認できます。",
  "Server monitoring": "サーバー監視",
  "See server health at a glance.": "サーバーの状態をひと目で確認。",
  "Monitor 3 servers for free; more with Pro": "3台まで無料。Proで追加可能",
  "View live CPU, memory, disk, and network metrics across your servers. No monitoring agent is required.": "複数サーバーのCPU、メモリ、ディスク、ネットワークをリアルタイムで監視。監視用エージェントは不要です。",
  "Compare authentication methods and device compatibility.": "認証方式とデバイスの互換性を比較。",
  "Free; compatible across macOS and iOS": "無料。macOSとiOSで互換",
  "Supports FIDO2 ECDSA-SK P-256 with shared credentials across macOS and iOS. The private key stays on the hardware key.": "FIDO2 ECDSA-SK P-256に対応し、認証情報をmacOSとiOSで共用できます。秘密鍵はハードウェアキー内に残ります。",
  "Platforms": "対応プラットフォーム",
  "Check device support and system requirements.": "対応デバイスとシステム要件を確認。",
  "Sync between devices": "デバイス間の同期",
  "Bring saved settings to your other devices.": "保存した設定を他のデバイスにも。",
  "iCloud sync · Pro": "iCloud同期 · Pro",
  "Sync Vault, monitoring configuration, and settings. Credentials use iCloud Keychain; chats and memory stay on the device.": "Vault、監視設定、各種設定を同期。認証情報にはiCloudキーチェーンを使い、チャットと記憶はデバイスに残ります。",
  "Paid plans": "有料プラン",
  "Compare recurring and one-time costs.": "継続課金と買い切りの費用を比較。",
  "Annual and lifetime plans unlock the same Pro features and include Family Sharing. AI model usage is billed separately.": "年間と買い切りで利用できるPro機能は同じで、どちらもファミリー共有に対応します。AIモデルの利用料は別途かかります。",
  "Working with a team": "チームでの利用",
  "Share access and work together.": "アクセスを共有し、共同で作業。",
  "A personal remote workspace": "個人向けリモートワークスペース",
  "Private sync for your own devices. No shared team vault or live multiplayer sessions.": "自分のデバイス間でプライベートに同期。チーム共有Vaultやリアルタイム共同セッションはありません。",
  "Connection types": "接続の種類",
  "Match protocols to your environment.": "環境に合うプロトコルを選択。",
  "SSH, Telnet, SFTP, and serial": "SSH、Telnet、SFTP、シリアル接続",
  "Core connections are free. Serial sessions are available on macOS; combine terminals and file browsers in a multi-pane workspace.": "基本接続は無料。macOSではシリアル接続も利用でき、ターミナルとファイルブラウザをマルチペインにまとめられます。",
  "Multiple sessions": "複数セッション",
  "Keep related sessions together.": "関連するセッションをひとつに。",
  "Multi-pane workspaces for free": "マルチペインを無料で利用",
  "On macOS, combine SSH, Telnet, SFTP, and serial sessions in a workspace and broadcast input to multiple terminals.": "macOSでSSH、Telnet、SFTP、シリアル接続をワークスペースにまとめ、複数ターミナルへ一括入力できます。",
  "Docker management": "Docker管理",
  "Choose how you work with containers.": "コンテナの操作方法を選択。",
  "Terminal commands and AI tools": "ターミナルコマンドとAIツール",
  "Run Docker commands through SSH, or let Pro’s Assistant investigate and act within your chosen permissions.": "SSHでDockerコマンドを実行。またはProのアシスタントに、選択した権限の範囲で調査と操作を任せられます。",
  "Compare Termind and ServerCat: server monitoring, SSH, Docker management, AI, hardware keys, Tailscale, sync, and pricing.": "TermindとServerCatを比較：サーバー監視、SSH、Docker管理、AI、ハードウェアキー、Tailscale、同期、価格。",
  "Free terminal access, lower upgrade costs.": "無料のターミナルと、手頃なアップグレード。",
  "Linux monitoring and Docker.": "Linux監視とDocker。",
  "A fit for detailed resource charts and a dedicated container dashboard. Premium adds the SSH terminal, sync, and container management.": "詳しいリソースグラフや専用コンテナダッシュボードを求める方に。PremiumではSSHターミナル、同期、コンテナ管理も利用できます。",
  "Linux and Docker monitoring for free": "LinuxとDockerの監視は無料",
  "Read CPU, GPU, memory, network, disk I/O, and Docker metrics over SSH. No monitoring agent is needed.": "SSH経由でCPU、GPU、メモリ、ネットワーク、ディスクI/O、Dockerのメトリクスを取得。監視用エージェントは不要です。",
  "SSH terminal · Premium": "SSHターミナル · Premium",
  "Monitoring connects over SSH for free. Interactive terminal sessions and background SSH require Premium.": "監視はSSH経由で無料。対話型ターミナルとバックグラウンドSSHにはPremiumが必要です。",
  "Dedicated Docker dashboard": "専用のDockerダッシュボード",
  "View container status and resource use for free. Premium adds container creation and management.": "コンテナの状態とリソース使用量は無料で確認。Premiumではコンテナの作成と管理も利用できます。",
  "No built-in AI features": "内蔵AI機能なし",
  "No AI command generator or conversational assistant.": "AIコマンド生成や対話型アシスタントはありません。",
  "Not supported": "非対応",
  "No built-in MCP server for exposing hosts or SSH tools to external agents.": "ホストやSSHツールを外部エージェントに公開する内蔵MCPサーバーはありません。",
  "No built-in Tailscale integration": "Tailscaleの内蔵連携なし",
  "Connect the device with a separate Tailscale client, then use the host’s Tailnet address. No in-app Tailnet login or device sync.": "別のTailscaleクライアントでデバイスを接続し、ホストのTailnetアドレスを使用します。アプリ内でのTailnetログインやデバイス同期はありません。",
  "No FIDO2 hardware-key support": "FIDO2ハードウェアキー非対応",
  "Supports software SSH keys, but not SSH signing with external FIDO2 keys.": "ソフトウェアSSH鍵に対応しますが、外部FIDO2キーによるSSH署名には対応しません。",
  "Monitoring targets Linux servers; some metrics are unavailable for other server operating systems.": "監視対象はLinuxサーバーです。他のサーバーOSでは一部のメトリクスを利用できません。",
  "iCloud sync · Premium": "iCloud同期 · Premium",
  "Sync encrypted connection data through iCloud across your devices.": "暗号化した接続データをiCloud経由でデバイス間に同期します。",
  "$5.99/year or $18.99 lifetime": "$5.99/年、または$18.99の買い切り",
  "Monitoring is free. Both Premium plans include the terminal, background SSH, sync, and container management.": "監視は無料。どちらのPremiumプランにも、ターミナル、バックグラウンドSSH、同期、コンテナ管理が含まれます。",
  "Compare Termind and WebSSH: SFTP, port forwarding, Tailscale, external AI clients, hardware keys, monitoring, and paid plans.": "TermindとWebSSHを比較：SFTP、ポート転送、Tailscale、外部AIクライアント、ハードウェアキー、監視、有料プラン。",
  "Lower lifetime price, more free connections.": "手頃な買い切り価格と、より多くの無料接続。",
  "Network tools and Proxmox.": "ネットワークツールとProxmox。",
  "A fit for Mosh, network diagnostics, VPN-over-SSH, and Proxmox workflows, with a one-time Pro purchase.": "Mosh、ネットワーク診断、VPN-over-SSH、Proxmoxを使う方に。Proは買い切りで購入できます。",
  "Free for one saved connection": "1件の接続保存まで無料",
  "Browse, transfer, and edit remote files. Pro lets you save unlimited connections.": "リモートファイルの閲覧、転送、編集に対応。Proでは保存できる接続数が無制限になります。",
  "Local and dynamic forwarding": "ローカル転送とダイナミック転送",
  "Use SSH tunnels to access remote services. VPN-over-SSH can route traffic from other iOS apps through a tunnel.": "SSHトンネルでリモートサービスにアクセス。VPN-over-SSHでは、他のiOSアプリの通信もトンネル経由にできます。",
  "Use a separate Tailscale client to reach Tailnet hosts. VPN-over-SSH is an SSH tunnel feature, not Tailnet integration.": "Tailnet上のホストへは、別のTailscaleクライアントで接続します。VPN-over-SSHはSSHトンネル機能であり、Tailnet連携ではありません。",
  "No AI command generator or conversational assistant. AI workflows require an external client connected through MCP.": "AIコマンド生成や対話型アシスタントはありません。AIでの作業には、MCPで接続した外部クライアントが必要です。",
  "Built-in API / MCP server": "内蔵API / MCPサーバー",
  "On macOS, external clients can read terminal output, send commands, and query IP addresses, DNS, Whois, and documentation.": "macOSで外部クライアントからターミナル出力の読み取り、コマンド送信、IPアドレス・DNS・Whois・ドキュメントの問い合わせができます。",
  "Proxmox monitoring and a terminal state bar": "Proxmox監視とターミナル状態バー",
  "Monitor Proxmox node CPU, memory, and storage, and view VM or LXC state. The terminal state bar can show custom status information.": "ProxmoxノードのCPU、メモリ、ストレージ、VMやLXCの状態を監視。ターミナル状態バーにはカスタム情報を表示できます。",
  "Also offers a local shell and serial connections on macOS, plus Ping, Traceroute, DNS, and Whois utilities.": "macOSではローカルシェルとシリアル接続も利用でき、Ping、Traceroute、DNS、Whoisのユーティリティもあります。",
  "YubiKey OTP": "YubiKey OTP",
  "Reads one-time passwords from a YubiKey over NFC. FIDO2 SSH signing with ECDSA-SK or Ed25519-SK is not supported.": "NFCでYubiKeyからワンタイムパスワードを読み取れます。ECDSA-SKやEd25519-SKによるFIDO2 SSH署名には非対応です。",
  "Use the same app on Mac, iPhone, and iPad.": "同じアプリをMac、iPhone、iPadで利用できます。",
  "Sync saved connections and the WebSSH database through iCloud.": "保存済み接続とWebSSHデータベースをiCloudで同期します。",
  "$15.00 lifetime Pro": "Pro買い切り $15.00",
  "The free tier saves one connection. Pro removes this limit on devices using the same Apple ID.": "無料プランで保存できる接続は1件です。Proでは、同じApple IDを使うデバイスでこの制限がなくなります。",
  "Termius is a trademark of Termius Corporation.": "TermiusはTermius Corporationの商標です。",
  "Compare Termind and Termius across SSH and SFTP, parallel transfers, Tailscale integration, AI, server monitoring, sync, and pricing.": "TermindとTermiusのSSHとSFTP、並列転送、Tailscale連携、AI、サーバー監視、同期、価格を比較します。",
  "Lower annual cost, with a lifetime option.": "手頃な年額と、買い切りの選択肢。",
  "Cross-platform and team access.": "幅広いOSとチーム利用。",
  "A fit for Windows, Linux, or Android users, and teams that need shared vaults and live terminal collaboration.": "Windows、Linux、Androidを使う方や、共有Vaultとターミナルでのリアルタイム共同作業が必要なチームに。",
  "SFTP included in Starter": "StarterにSFTPを含む",
  "Browse remote files and transfer files over SFTP.": "リモートファイルを閲覧し、SFTPで転送できます。",
  "Files can be transferred through the SFTP file browser.": "SFTPファイルブラウザからファイルを転送できます。",
  "Port forwarding included in Starter": "Starterにポート転送を含む",
  "Access remote services through SSH tunnels.": "SSHトンネルでリモートサービスにアクセスできます。",
  "Connect through a separate Tailscale client before accessing Tailnet hosts.": "Tailnet上のホストにアクセスする前に、別のTailscaleクライアントで接続します。",
  "AI-powered autocomplete": "AIによる自動補完",
  "Included in Starter. Get suggestions for commands, arguments, and file paths.": "Starterに含まれます。コマンド、引数、ファイルパスの候補を表示します。",
  "No built-in MCP server for exposing hosts or SSH/SFTP tools to external agents.": "ホストやSSH/SFTPツールを外部エージェントに公開する内蔵MCPサーバーはありません。",
  "No built-in dashboard for live server metrics.": "サーバーメトリクスをリアルタイム表示する内蔵ダッシュボードはありません。",
  "Included in Starter": "Starterに含まれる",
  "Supports FIDO2 hardware keys, but credentials used on iOS are incompatible with Termius on other platforms.": "FIDO2ハードウェアキーに対応しますが、iOSで使う認証情報は他のプラットフォームのTermiusと互換性がありません。",
  "Desktop and mobile, across ecosystems.": "さまざまなOSのデスクトップとモバイルに対応。",
  "Personal cloud vault · Pro": "個人用クラウドVault · Pro",
  "Sync across desktop and mobile through Termius’s encrypted vault.": "Termiusの暗号化Vault経由で、デスクトップとモバイル間を同期します。",
  "$10/month, billed annually": "月額$10、年払い",
  "Pro costs $120 per year. Team and business plans are available separately.": "Proは年間$120です。チーム向けとビジネス向けのプランは別途提供されています。",
  "Shared vaults & live collaboration": "共有Vaultとリアルタイム共同作業",
  "Team includes a shared vault, live collaboration, shared session logs, and consolidated billing.": "Teamには共有Vault、リアルタイム共同作業、セッションログの共有、一括請求が含まれます。",
  "Prompt is a registered trademark of Panic Inc.": "PromptはPanic Inc.の登録商標です。",
  "Compare Termind and Prompt 3: SSH and Mosh, AI, FIDO2 hardware keys, port forwarding, Tailscale, sync, and pricing.": "TermindとPrompt 3を比較：SSHとMosh、AI、FIDO2ハードウェアキー、ポート転送、Tailscale、同期、価格。",
  "Lower purchase price, FIDO2 creation on iOS.": "手頃な購入価格と、iOSでのFIDO2鍵生成。",
  "Mosh and Eternal Terminal.": "MoshとEternal Terminal。",
  "A fit for changing networks, YubiKey PIV or Ed25519-SK authentication, and terminal access on Apple Vision Pro.": "ネットワークの切り替え、YubiKey PIVやEd25519-SK認証、Apple Vision Proでのターミナル利用を求める方に。",
  "Mosh and Eternal Terminal help sessions survive unstable networks. Local shell sessions are available on macOS.": "MoshとEternal Terminalは、不安定なネットワークでもセッションを維持できます。macOSではローカルシェルも利用できます。",
  "SSH port forwarding": "SSHポート転送",
  "Set up SSH tunnels and use jump hosts to reach servers behind another host.": "SSHトンネルを設定し、踏み台ホストを使って別のホストの先にあるサーバーへ接続できます。",
  "Use a separate Tailscale client before connecting. VPN on Demand activates a configured system VPN; it does not manage a Tailnet.": "接続前に別のTailscaleクライアントを使います。VPNオンデマンドは設定済みのシステムVPNを起動する機能で、Tailnetを管理するものではありません。",
  "Omniview and terminal tabs": "Omniviewとターミナルタブ",
  "On macOS, see multiple terminal tabs together and send commands to more than one session from Omniview.": "macOSのOmniviewで複数のターミナルタブを並べて表示し、複数セッションへコマンドを送信できます。",
  "YubiKey PIV and FIDO2": "YubiKey PIVとFIDO2",
  "Supports YubiKey PIV and FIDO2 ECDSA-SK / Ed25519-SK. FIDO2 key generation requires macOS. On iOS, FIDO2 works over NFC or Lightning, not USB-C.": "YubiKey PIVとFIDO2 ECDSA-SK / Ed25519-SKに対応します。FIDO2鍵の生成にはmacOSが必要です。iOSではNFCまたはLightning経由でFIDO2を使えますが、USB-Cには対応しません。",
  "One purchase covers Mac, iPhone, iPad, and Apple Vision Pro.": "1回の購入でMac、iPhone、iPad、Apple Vision Proを利用できます。",
  "Sync saved servers, passwords, SSH keys, and Clips across your devices.": "保存済みサーバー、パスワード、SSH鍵、Clipsをデバイス間で同期します。",
  "$9.99/year or $49.99 one-time": "$9.99/年、または$49.99の買い切り",
  "Includes a 7-day trial. An active annual subscription also covers future major versions.": "7日間のトライアル付き。有効な年間サブスクリプションには、将来のメジャーバージョンも含まれます。",
  "What can I do with Termind?": "Termindでは何ができますか？",
  "Termind is an AI-driven remote workspace. Describe a command, ask the AI Assistant to investigate an issue or act on a server, then keep working with SSH, Telnet, SFTP, and live metrics in the same app. AI helps with the work; you choose the model, permissions, and workflow.": "TermindはAIを活用するリモートワークスペースです。必要なコマンドを言葉で伝えたり、AIアシスタントに問題の調査やサーバー操作を依頼したり。そのまま同じアプリでSSH、Telnet、SFTP、リアルタイム監視を使って作業を続けられます。AIは作業を支援し、モデル、権限、進め方はあなたが決めます。",
  "How is the AI Assistant different from Command Generator?": "AIアシスタントとコマンド生成の違いは何ですか？",
  "Command Generator is for “write me a command”: describe what you need, review the result, and decide whether to run it. It stays free and never presses Return for you.": "コマンド生成は「コマンドを書いてほしい」ときの機能です。必要なことを説明し、結果を確認してから実行するかを決めます。無料で使え、勝手にReturnキーを押すことはありません。",
  "The AI Assistant handles multi-step tasks, such as checking a service, reading logs, and running commands or working with files under the permissions you set. It is a Pro feature and can use skills, Web Search, remote MCP tools, and Hermes Memory to help you get the job done—not just suggest what to do.": "AIアシスタントは、サービスの確認、ログの読み取り、設定した権限でのコマンド実行やファイル操作など、複数手順の作業に対応します。Pro機能で、スキル、ウェブ検索、リモートMCPツール、Hermes Memoryも活用し、提案だけでなく作業の完了を支援します。",
  "What is Hermes Memory? Do I have to repeat myself in every chat?": "Hermes Memoryとは？毎回同じ説明が必要ですか？",
  "Hermes Memory lets the AI Assistant carry useful context and preferences across conversations, such as how you work or details about your environment. The Assistant searches saved memory when it is relevant and can search past chats, so you can spend less time explaining the same background.": "Hermes Memoryを使うと、AIアシスタントが作業の進め方や環境の情報など、有用な背景や好みを会話をまたいで保持できます。必要に応じて保存済みの記憶や過去のチャットを検索するため、同じ背景を繰り返し説明する手間を減らせます。",
  "It is off by default. The memory store stays on this device and does not sync through iCloud. You can review, edit, export, or destroy it at any time, and turn off Automatic Learning. Automatic Learning may incur additional API charges.": "初期設定ではオフです。記憶はこのデバイスに保存され、iCloudでは同期しません。いつでも確認、編集、エクスポート、全削除ができ、自動学習もオフにできます。自動学習には追加のAPI利用料がかかる場合があります。",
  "Can the AI run commands without asking me?": "AIが確認なしでコマンドを実行することはありますか？",
  "That depends on the permissions you choose. Command Generator never runs commands. The AI Assistant follows tool policies and your permission mode: actions requiring approval can come to you for confirmation or go to a security-review model. Full Access allows those actions without asking each time. Review the scope of access before you use it, especially on production servers.": "選択した権限によります。コマンド生成はコマンドを実行しません。AIアシスタントはツールポリシーと権限モードに従い、承認が必要な操作はユーザーによる確認、または安全性を審査するモデルに回せます。「完全アクセス」では毎回の確認なしに操作できます。特に本番サーバーで使う前には、アクセス範囲を確認してください。",
  "Do I need my own API key to use AI?": "AIの利用には自分のAPIキーが必要ですか？",
  "Yes. Termind uses bring-your-own-key (BYOK): configure your model endpoint, model, and API key. It supports Chat Completions, Responses, Messages, and generateContent protocols. No Termind account is needed. Pro does not include third-party model usage; your AI provider bills that separately.": "はい。Termindは自分のキーを使うBYOK方式です。モデルのエンドポイント、モデル、APIキーを設定してください。Chat Completions、Responses、Messages、generateContentの各プロトコルに対応しています。Termindアカウントは不要です。Proに第三者モデルの利用料は含まれず、AIプロバイダーから別途請求されます。",
  "Can I use Termind without AI?": "AIなしでもTermindを使えますか？",
  "Absolutely. SSH and Telnet terminals, SFTP file management, snippets, and port forwarding work without an AI key. The AI Assistant, Hermes Memory, Web Search, and MCP connections are optional—turn on only what you need.": "もちろんです。SSHとTelnetのターミナル、SFTPファイル管理、スニペット、ポート転送はAIキーなしで使えます。AIアシスタント、Hermes Memory、ウェブ検索、MCP接続は任意なので、必要なものだけ有効にしてください。",
  "Are the features the same on Mac, iPhone, and iPad?": "Mac、iPhone、iPadで機能は同じですか？",
  "Termind supports macOS 15, iOS 18, and iPadOS 18 or later. All three offer SSH, Telnet, SFTP, server metrics, the AI Assistant, and built-in Tailscale, with some features requiring Pro. Mac also offers serial sessions, multi-pane workspaces, and input broadcasting for free. Its built-in MCP server requires Pro. Each iPhone or iPad workspace contains one SSH, Telnet, or SFTP session.": "TermindはmacOS 15、iOS 18、iPadOS 18以降に対応しています。いずれもSSH、Telnet、SFTP、サーバー監視、AIアシスタント、内蔵Tailscaleが利用でき、一部の機能にはProが必要です。Macではシリアル接続、マルチペイン、一括入力も無料です。内蔵MCPサーバーにはProが必要です。iPhoneとiPadでは、各ワークスペースにSSH、Telnet、SFTPのいずれか1セッションを開きます。",
  "Do I need to install anything on my server?": "サーバーに何かインストールする必要はありますか？",
  "No Termind agent or daemon is required. Standard connections need a working SSH or Telnet service, plus SFTP support for file management. To connect through built-in Tailscale, the server must run Tailscale with Tailscale SSH enabled. Optional SSH Shell Integration runs only in the current shell session: it leaves no background process after disconnecting and does not change shell configuration files.": "Termindのエージェントや常駐デーモンは不要です。通常の接続には動作するSSHまたはTelnetサービスが、ファイル管理にはSFTP対応が必要です。内蔵Tailscale経由で接続するには、サーバーでTailscaleを実行し、Tailscale SSHを有効にしてください。任意のSSHシェル統合は現在のシェルセッション内だけで動作し、切断後にバックグラウンドプロセスを残したり、シェル設定ファイルを書き換えたりしません。",
  "How do I connect my Tailnet? Do I need the Tailscale app?": "Tailnetに接続するには？Tailscaleアプリは必要ですか？",
  "Built-in Tailscale is a Termind Pro feature. No separate Tailscale app or system VPN setup is needed on this device; Termind establishes the connection within the app.": "内蔵TailscaleはTermind Proの機能です。このデバイスに別のTailscaleアプリを入れたり、システムVPNを設定したりする必要はなく、Termindがアプリ内で接続します。",
  "Create or edit a group in Vault, enable Tailscale, sign in through your browser or use an Auth Key, then save the group. Discovered Tailnet devices appear in that group. You can connect different groups to different tailnets.": "Vaultでグループを作成または編集し、Tailscaleを有効にして、ブラウザでログインするかAuth Keyを入力してからグループを保存します。検出したTailnetデバイスがそのグループに表示されます。グループごとに異なるTailnetへ接続することもできます。",
  "The target server must have Tailscale SSH enabled, and your Tailnet’s access policies must allow the username you connect with. You can then open an SSH terminal or use SFTP. Device details also show online status, MagicDNS names, and Ping latency. Tailnet sign-in stays on the current device, so sign in again when you switch devices.": "接続先でTailscale SSHが有効になっており、接続に使うユーザー名がTailnetのアクセスポリシーで許可されている必要があります。その後、SSHターミナルやSFTPを利用できます。デバイス詳細にはオンライン状態、MagicDNS名、Pingの遅延も表示されます。Tailnetのログイン状態は現在のデバイスだけに保存されるため、別のデバイスでは再ログインが必要です。",
  "What is free, and what does Pro add?": "無料で使える機能とProの違いは？",
  "Core SSH, Telnet, SFTP, terminal uploads, snippets, Command Generator, and port forwarding stay free, as do serial sessions, multi-pane workspaces, and input broadcasting on Mac. If you just need to connect to a server or move a few files, you can get started right away.": "基本のSSH、Telnet、SFTP、ターミナルからのアップロード、スニペット、コマンド生成、ポート転送は無料です。Macのシリアル接続、マルチペイン、一括入力も無料。サーバーへの接続や少量のファイル転送なら、すぐに使い始められます。",
  "Pro unlocks built-in Tailscale, multi-connection acceleration for SFTP and for port forwarding on Mac, the AI Assistant with optional Hermes Memory, monitoring for more than 3 servers, remote MCP clients, iCloud sync for Vault, Metrics, and settings, plus the built-in MCP server on Mac. Core file transfers and forwarding, multiple sessions, and multiple forwarding rules stay free. Choose an annual plan or a one-time lifetime purchase; both support Family Sharing. Third-party AI usage is billed separately.": "Proでは内蔵Tailscale、SFTPとMacのポート転送の複数接続による高速化、任意のHermes Memoryに対応するAIアシスタント、4台以上のサーバー監視、リモートMCPクライアント、Vault・メトリクス・設定のiCloud同期、Macの内蔵MCPサーバーが使えます。基本のファイル転送とポート転送、複数セッション、複数の転送ルールは引き続き無料です。年間プランと買い切りを選べ、どちらもファミリー共有に対応します。第三者AIの利用料は別途かかります。",
  "Where are my passwords and SSH private keys stored?": "パスワードとSSH秘密鍵はどこに保存されますか？",
  "In Apple’s Data Protection Keychain, separate from your host information. Passwords and software SSH private keys can stay on this device or sync through iCloud Keychain. Secure Enclave private keys cannot be exported and do not sync. SSH private keys are not sent to the AI model as chat context.": "ホスト情報とは別に、Appleのデータ保護キーチェーンに保存します。パスワードとソフトウェアSSH秘密鍵は、このデバイスのみに保存するか、iCloudキーチェーンで同期できます。Secure Enclave秘密鍵はエクスポートも同期もできません。SSH秘密鍵をチャットのコンテキストとしてAIモデルへ送信することはありません。",
  "What carries over when I switch devices?": "デバイスを変えると、何が引き継がれますか？",
  "With Pro’s iCloud sync enabled, you can sync Vault, Metrics configuration, and settings: hosts, snippets, port forwards, monitoring layouts, terminal appearance, Connections, AI models, MCP clients, skills, and Web Search preferences. Connections preferences include SSH Max Sessions and file-transfer concurrency. You choose which categories to sync.": "ProのiCloud同期を有効にすると、Vault、メトリクス設定、各種設定を同期できます。ホスト、スニペット、ポート転送、監視レイアウト、ターミナルの外観、接続設定、AIモデル、MCPクライアント、スキル、ウェブ検索設定が対象です。接続設定にはSSH Max Sessionsとファイル転送の同時実行数も含まれます。同期するカテゴリは選択できます。",
  "With Settings sync enabled, AI API keys and remote MCP client tokens sync through iCloud Keychain. Chats, Hermes Memory, live metric samples, and connection state do not sync. The Mac’s built-in MCP server settings and token also stay on that device.": "設定の同期を有効にすると、AI APIキーとリモートMCPクライアントのトークンはiCloudキーチェーンで同期されます。チャット、Hermes Memory、リアルタイムのメトリクスサンプル、接続状態は同期されません。Mac内蔵MCPサーバーの設定とトークンも、そのデバイスに残ります。",
  "What goes to the model when I use AI or Memory?": "AIや記憶機能を使うと、何がモデルに送られますか？",
  "Termind connects directly to your selected AI provider, with no hosted Termind AI service in between. Requests may include your messages, attachments, session context, and command output or file contents you authorize it to read. The provider’s own policies govern how it handles and retains that data.": "Termindは選択したAIプロバイダーへ直接接続し、Termindが運営するAIサービスを経由しません。リクエストには、メッセージ、添付ファイル、セッションのコンテキスト、読み取りを許可したコマンド出力やファイル内容が含まれる場合があります。データの取り扱いと保持には、提供者のポリシーが適用されます。",
  "Local memory storage does not mean memory never leaves your device. When enabled, retrieved memory entries or chat excerpts may be sent to the model as context. Automatic Learning also sends relevant conversation content and selected existing memory to your configured learning model. Keep only information you are comfortable sharing with that provider.": "記憶をローカルに保存することは、記憶がデバイス外に送られないという意味ではありません。有効にすると、検索した記憶やチャットの抜粋をコンテキストとしてモデルへ送信する場合があります。自動学習では、関連する会話の内容と選択した既存の記憶も、設定した学習用モデルへ送信します。その提供者と共有してよい情報だけを保存してください。",
  "Web Search can be turned off in settings. When enabled, queries and selected page content are sent to search services and your AI provider. See the Privacy Policy for the complete data flow.": "ウェブ検索は設定でオフにできます。有効な場合、検索クエリと選択したページ内容が検索サービスやAIプロバイダーへ送信されます。データの流れの詳細はプライバシーポリシーをご覧ください。",
  "Where can I get help?": "どこでサポートを受けられますか？",
  "Visit Support or email support-termind@akinokaede.com. Tell us what you were trying to do, what happened, and which device and OS version you use. Before sharing screenshots or logs, remove passwords, keys, host addresses, and other sensitive details.": "サポートページ、またはsupport-termind@akinokaede.comへご連絡ください。試した操作、起きたこと、デバイスとOSのバージョンをお知らせください。スクリーンショットやログを共有する前に、パスワード、鍵、ホストアドレスなどの機密情報を取り除いてください。"
};
